apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wrtc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-wrtc@sha256:d427d6bfc1b8f5cc2a9c94c01f33b21deee662af3977319c7dc30efab184b447
        name: my-nodejs
        resources: {}
status: {}
